trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:
- checkout: self
  lfs: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip poetry keyring artifacts-keyring
  displayName: 'Install package and tools'

- script: |
    poetry install
  condition: always()

- script: |
    poetry run make lint
  displayName: 'Check for style'

- script: |
    poetry run make test
  displayName: 'Run regression tests'
